### ISSUE TITLE
don't bother to make it run

### ISSUE THREAD

**Issue by AndreiD** [api3dao/qrng-example#9]
documentation is outdated, ...

**Comment by Ashar2shahid** [comment]
I've updated the dependencies, it should work now

**Comment by AndreiD** [comment]
while it might, it shows that this project is not maintained. How can someone **TRUST** you with randomness if you don't maintain the project.

**Comment by Ashar2shahid** [comment]
this is a example repo, sometimes examples fall out of date because we are actively developing the product and improving it.  documentation problems occur here and there but that doesn't mean we are not actively working on the product.
